# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56091d96a495bfe4acee71b2a92bf3837ab67b59bae1dd8793a63a0bfa289017344408474b9f033954b7235d6c55eabbb71c775103b78cd2a0a7b99e251ed6d0

test:
  secret_key_base: 047d28d5c995de30f157791e459c7bd4eead5b8db99dbaaefc5b6db9902b2675f412f8235494d73bc0b617321c1655ba9772bf00c15a137286178be537f9c54a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
